<?php

return [
    "A Level Biology",
    "A Level Chemistry",
    "A Level Maths",
    "ACT",
    "American Culture",
    "American Literature",
    "AMERICAN READING",
    "AP",
    "AP BIO",
    "AP Calculus",
    "AP Chemistry",
    "AP CS",
    "AP History",
    "AP Human Geography",
    "AP Macro",
    "AP Micro",
    "AP Physics",
    "AP Statistics",
    "Business Analysis",
    "Computer Science",
    "Creative Writing",
    "Debate",
    "ELA",
    "ESL",
    "FCE",
    "Financial Accounting",
    "GLOBAL ENGLISH & SCIENCE 6",
    "Gmat",
    "Grammar",
    "IB",
    "IB Chemistry",
    "IB Economics",
    "IB Math",
    "IELTS",
    "IGCSE ESL",
    "IGCSE Math",
    "IGCSE Science",
    "IGCSE Spanish",
    "Literature",
    "Math",
    "Persuasive writing",
    "PET",
    "Reading",
    "Reading & Writing",
    "Reading Literature",
    "SAT",
    "SCIENCE",
    "Social Issues",
    "Spanish",
    "Speak Out",
    "Speaking",
    "SSAT",
    "SSAT Math",
    "SSAT Verbal",
    "Tiếng Việt",
    "TOEFL",
    "TOEIC",
    "Tutor DH",
    "Vocab IELTS+ GMAT",
    "Writing",
    "Writing & Present",
    "WSC",
];