<?php
    return [
        "Samoa thuộc Mỹ",
        "Việt Nam (Đại học quốc tế)",
        "Canada",
        "Úc",
        "Hà Lan",
        "Anh",
        "Antilles Hà Lan",
        "Singapore",
        "Afghanistan",
        "Albania",
        "Algeria",
        "Andorra",
        "Angola",
        "Anguilla",
        "Nam Cực",
        "Antigua và Barbuda",
        "Argentina",
        "Armenia",
        "Aruba",
        "Áo",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Bỉ",
        "Belize",
        "Benin",
        "Bermuda",
        "Bhutan",
        "Bolivia",
        "Bosnia và Herzegovina",
        "Botswana",
        "Đảo Bouvet",
        "Brazil",
        "Lãnh thổ Ấn Độ Dương thuộc Anh",
        "Brunei Darussalam",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Campuchia",
        "Cameroon",
        "Cape Verde",
        "Quần đảo Cayman",
        "Cộng hòa Trung Phi",
        "Chad",
        "Chile",
        "Trung Quốc",
        "Đảo Giáng Sinh",
        "Quần đảo Cocos (Keeling)",
        "Colombia",
        "Comoros",
        "Congo",
        "Congo, Cộng hòa Dân chủ Congo",
        "Quần đảo Cook",
        "Costa Rica",
        "Bờ Biển Ngà",
        "Croatia (Hrvatska)",
        "Cuba",
        "Síp",
        "Cộng hòa Séc",
        "Đan Mạch",
        "Djibouti",
        "Dominica",
        "Cộng hòa Dominica",
        "Timor-Leste",
        "Ecuador",
        "Ai Cập",
        "El Salvador",
        "Guinea Xích Đạo",
        "Eritrea",
        "Estonia",
        "Ethiopia",
        "Quần đảo Falkland (Malvinas)",
        "Quần đảo Faroe",
        "Fiji",
        "Phần Lan",
        "Pháp",
        "Pháp Metropolitan",
        "Guyane thuộc Pháp",
        "Polynésie thuộc Pháp",
        "Lãnh thổ Nam cực thuộc Pháp",
        "Gabon",
        "Gambia",
        "Georgia",
        "Đức",
        "Ghana",
        "Gibraltar",
        "Hy Lạp",
        "Greenland",
        "Grenada",
        "Guadeloupe",
        "Guam",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Đảo Heard và Quần đảo McDonald",
        "Thánh Thể (Thành phố Vatican)",
        "Honduras",
        "Hồng Kông",
        "Hungary",
        "Iceland",
        "Ấn Độ",
        "Indonesia",
        "Iran (Cộng hòa Hồi giáo Iran)",
        "Iraq",
        "Ireland",
        "Israel",
        "Italy",
        "Jamaica",
        "Nhật Bản",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "Cộng hòa Dân chủ Nhân dân Triều Tiên",
        "Hàn Quốc",
        "Kuwait",
        "Kyrgyzstan",
        "Lào, Cộng hòa Dân chủ Nhân dân",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libyan Arab Jamahiriya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Mỹ",
        "Macau",
        "Macedonia, Cộng hòa cũ Jugoslavia",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Quần đảo Marshall",
        "Martinique",
        "Mauritania",
        "Mauritius",
        "Mayotte",
        "Mexico",
        "Micronesia, Các tiểu bang liên bang",
        "Moldova, Cộng hòa Moldova",
        "Monaco",
        "Mongolia",
        "Montserrat",
        "Morocco",
        "Mozambique",
        "Myanmar",
        "Namibia",
        "Nauru",
        "Nepal",
        "New Caledonia",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "Niue",
        "Đảo Norfolk",
        "Quần đảo Bắc Mariana",
        "Na Uy",
        "Oman",
        "Pakistan",
        "Palau",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Pitcairn",
        "Ba Lan",
        "Bồ Đào Nha",
        "Puerto Rico",
        "Qatar",
        "Réunion",
        "Romania",
        "Liên bang Nga",
        "Rwanda",
        "Saint Kitts và Nevis",
        "Saint Lucia",
        "Saint Vincent và Grenadines",
        "Samoa",
        "San Marino",
        "Sao Tome và Principe",
        "Arabia Xaudite",
        "Senegal",
        "Seychelles",
        "Sierra Leone",
        "Slovakia (Cộng hòa Slovakia)",
        "Slovenia",
        "Quần đảo Solomon",
        "Somalia",
        "Nam Phi",
        "Quần đảo Nam Georgia và Quần đảo Sandwich Nam",
        "Tây Ban Nha",
        "Sri Lanka",
        "St. Helena",
        "St. Pierre và Miquelon",
        "Sudan",
        "Suriname",
        "Quần đảo Svalbard và Jan Mayen",
        "Swaziland",
        "Thụy Điển",
        "Thụy Sĩ",
        "Cộng hòa Ả Rập Syria",
];