<?php
    return [
        "Connor Kiệt (Connor James Kenney)",
        "Trương Thị Thanh Tâm",
        "Nguyễn Đình Hóa",
        "Trần Khánh Linh",
        "Ross Campell",
        "Jonathan Keselica",
        "Nguyễn Thị Hồng Hạnh",
        "Hà Anh Phương",
        "Nguyễn Thị Thu Thảo",
        "Nguyễn Thị Chinh",
        "Lê Điều Thu Giang",
        "Lê Thị Sơn Trà",
        "Vũ Việt Dũng",
        "Nguyễn Hoài Thu",
        "Sophia El Bouzidi",
        "Vũ Minh Tuấn",
        "Hoàng Ngọc Trâm",
        "Nadir Ayoub Agouri",
        "Nguyễn Hữu Đức Trung",
        "Lê Thành An",
        "Nguyễn Việt Tiệp",
        "Denis Tau",
        "Lester Glazier",
        "Đỗ Thu Hà",
        "Test cuối khóa",
        "Bùi Thái Sơn",
        "Chu Thành Đạt",
        "Nguyễn Minh Lâm",
        "Jenna Bateman",
        "Bruce Labeeuw",
        "Matthew Clive Jelf",
        "Jacqueline Gilbertson",
        "Đỗ Đức Tâm",
        "Nguyễn Kiến Quân",
        "Nguyễn Minh Đức",
        "Ngô Ngọc Khánh",
        "Nguyễn Phú Quang",
        "Tạ Thị Huê",
        "Phạm Thị Thanh Hường",
        "Candice Aucamp",
        "Đỗ Thị Khánh Vân",
        "Hoàng Trung Hiếu",
        "Cash Howard",
        "Trần Phương Thảo",
        "Zach Patzig",
        "Đặng Anh Khuê",
        "GV Thuê Ngoài",
        "Trần Thị Thu Trang",
        "Vũ Hoàng Minh",
        "Nguyễn Thiên Trang",
        "Hazel Schaeffer",
        "Sampson German",
        "Jessica De Lauder",
        "Nguyễn Trọng Tài",
        "Mạc Văn Đạt",
        "Lê Ngọc Thắng",
        "mid term",
        "Lương Hồng Phượng",
        "Trần Thị Minh Ánh",
        "Nguyễn Quý Thịnh",
        "Đoàn Phương Hoa",
        "Bùi Hoàng Linh",
        "Hoàng Mai Duy",
        "Đặng Thị Thùy Linh",
        "Luyện đề",
        "Nguyễn Hữu Độ",
        "Trần Thị Hoài",
        "Hà Thị Thu Hương",
        "Daria Kungurova"
    ]
?>