<?php
return [
    "A Level Biology",
    "A Level Chemistry",
    "A Level Maths",
    "ACT",
    "American Culture",
    "American Literature",
    "AMERICAN READING",
    "AP",
    "AP BIO",
    "AP Calculus",
    "AP Chemistry",
    "AP CS",
    "AP History",
    "AP Human Geography",
    "AP Macro",
    "AP Micro",
    "AP Physics",
    "AP Statistics",
    "BẢO LƯU",
    "Business Analysis",
    "Computer Science",
    "Creative Writing",
    "Debate",
    "ELA",
    "ESL",
    "FCE",
    "Financial Accounting",
    "GLOBAL ENGLISH & SCIENCE 6",
    "Gmat",
    "Grammar",
    "IB",
    "IB Chemistry",
    "IB Economics",
    "IB Math",
    "IELTS",
    "IGCSE ESL",
    "IGCSE Math",
    "IGCSE Science",
    "IGCSE Spanish",
    "Literature",
    "Math",
    "Persuasive writing",
    "PET",
    "Presentation",
    "Reading",
    "Reading & Writing",
    "Reading Literature",
    "SAT",
    "SCIENCE",
    "Social Issues",
    "Spanish",
    "Speak Out",
    "Speaking",
    "SSAT",
    "SSAT Math",
    "SSAT Verbal",
    "Tiếng Việt",
    "TOEFL",
    "TOEIC",
    "Tutor DH",
    "Vocab IELTS+ GMAT",
    "Writing",
    "Writing & Present",
    "WSC",
    "English In Motion",
    "Flyers",
    "IPA",
    "KET",
    "Kid's Box",
    "Leadership",
    "Market Leader",
    "Math & Science",
    "MOVERS",
    "Ollie",
    "Story Telling",
    "Coding",
    "Lập trình",
    "Roblox",
    "CAE",
    "College writing",
    "Edits",
    "ESSAY",
    "Interview",
    "Luận",
    "Supp essay",
    "Inova",
    "Viết báo",
    "Sản phẩm công nghệ",
    "Từ thiện",
    "Trải nghiệm văn hóa",
    "Phát triển bản thân",
    "Chụp ảnh",
    "Thiết kế",
    "Vẽ chì",
    "Vẽ màu nước",
    "Vẽ màu Acrylic",
    "Vẽ màu tổng hợp",
    "Hát",
    "Múa",
    "Nhảy",
    "Đàn tính",
    "Guitar",
    "Piano",
    "Violin",
    "Múa mâm",
    "Nhạc cụ đàn tranh",
    "Nhạc cụ khèn",
    "Portfolio",
    "Tư vấn định hướng ngoại khóa"
]
    ?>